<?php
// Auto-generated by scripts/deploy.sh — do not edit by hand.
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-store');
echo json_encode(['version' => '1.0.26', 'date' => '2026-07-13']);
