#!/usr/bin/env bash
#
# One-shot release: bump version -> stamp app + server -> build/install app ->
# deploy server to the VM -> print the version.
#
# Usage:
#   scripts/deploy.sh            # bump patch (x.y.Z -> x.y.Z+1), build & deploy
#   scripts/deploy.sh --no-bump  # deploy current VERSION without bumping
#
set -euo pipefail

cd "$(dirname "$0")/.."   # repo root

# ---- config ----
VM_IP="192.168.178.207"
VM_USER="root"
VM_PATH="/var/www/html/teamworkshow"
KEY="$HOME/.ssh/teamworkshow_deploy"
JAVA_HOME_DEFAULT="/Applications/Android Studio.app/Contents/jbr/Contents/Home"

# ---- bump version ----
VERSION="$(tr -d '[:space:]' < VERSION)"
if [ "${1:-}" != "--no-bump" ]; then
  IFS='.' read -r MA MI PA <<< "$VERSION"
  PA=$(( ${PA:-0} + 1 ))
  VERSION="${MA:-1}.${MI:-0}.${PA}"
  printf '%s\n' "$VERSION" > VERSION
fi
DATE="$(date +%Y-%m-%d)"
echo ">> Version: $VERSION ($DATE)"

# ---- stamp server version ----
cat > server/php/version.php <<PHP
<?php
// Auto-generated by scripts/deploy.sh — do not edit by hand.
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-store');
echo json_encode(['version' => '$VERSION', 'date' => '$DATE']);
PHP

# ---- build + install app (reads VERSION for versionName) ----
export JAVA_HOME="${JAVA_HOME:-$JAVA_HOME_DEFAULT}"
echo ">> Building app…"
./gradlew installDebug --console=plain -q

# ---- deploy server to VM ----
echo ">> Deploying server to $VM_USER@$VM_IP…"
scp -i "$KEY" -o BatchMode=yes \
  server/php/playlist.php server/php/media.php server/php/upload.php \
  server/php/delete.php server/php/version.php server/php/index.html \
  "$VM_USER@$VM_IP:$VM_PATH/"
ssh -i "$KEY" -o BatchMode=yes "$VM_USER@$VM_IP" "chown -R www-data:www-data $VM_PATH"

echo ""
echo "==================================================="
echo "  Deployed Teamwork Show  v$VERSION  ($DATE)"
echo "  App     -> installed on the connected device"
echo "  Server  -> http://$VM_IP/teamworkshow/"
echo "==================================================="
