#!/usr/bin/env bash
#
# One-shot release: bump version -> stamp app + server -> build/install app ->
# deploy server to the VM -> print the version.
#
# Usage:
#   scripts/deploy.sh            # bump patch (x.y.Z -> x.y.Z+1), build & deploy
#   scripts/deploy.sh --no-bump  # deploy current VERSION without bumping
#
set -euo pipefail

cd "$(dirname "$0")/.."   # repo root

# ---- config ----
# Deploy target defaults to the legacy VM; override via gitignored scripts/deploy.env
# (see scripts/deploy.env.sample) to push to All-Inkl instead.
DEPLOY_HOST="192.168.178.207"
DEPLOY_USER="root"
DEPLOY_PATH="/var/www/html/teamworkshow"
DEPLOY_KEY="$HOME/.ssh/teamworkshow_deploy"
DEPLOY_PORT="22"
DEPLOY_CHOWN="www-data:www-data"   # empty on hosts without root
if [ -f scripts/deploy.env ]; then
  # shellcheck disable=SC1091
  . scripts/deploy.env
fi
JAVA_HOME_DEFAULT="/Applications/Android Studio.app/Contents/jbr/Contents/Home"

# ---- flags: --no-bump (deploy current VERSION) / --server-only (skip app build) ----
BUMP=1; SERVER_ONLY=0
for arg in "$@"; do
  case "$arg" in
    --no-bump)     BUMP=0 ;;
    --server-only) BUMP=0; SERVER_ONLY=1 ;;
  esac
done

# ---- bump version ----
VERSION="$(tr -d '[:space:]' < VERSION)"
if [ "$BUMP" = "1" ]; then
  IFS='.' read -r MA MI PA <<< "$VERSION"
  PA=$(( ${PA:-0} + 1 ))
  VERSION="${MA:-1}.${MI:-0}.${PA}"
  printf '%s\n' "$VERSION" > VERSION
fi
DATE="$(date +%Y-%m-%d)"
echo ">> Version: $VERSION ($DATE)"

# ---- stamp server version ----
cat > server/php/version.php <<PHP
<?php
// Auto-generated by scripts/deploy.sh — do not edit by hand.
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-store');
echo json_encode(['version' => '$VERSION', 'date' => '$DATE']);
PHP

# ---- build + install app (reads VERSION for versionName); skipped for --server-only ----
if [ "$SERVER_ONLY" = "0" ]; then
  export JAVA_HOME="${JAVA_HOME:-$JAVA_HOME_DEFAULT}"
  echo ">> Building app…"
  ./gradlew installDebug --console=plain -q
else
  echo ">> --server-only: skipping app build/install"
fi

# ---- deploy server to VM ----
# Push every PHP endpoint (public + admin/CRUD). config.php is VM-only and not in
# the repo, so this never clobbers the live secrets; media/ uploads are untouched.
echo ">> Deploying server to $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH…"
SSH="ssh -i $DEPLOY_KEY -p $DEPLOY_PORT -o BatchMode=yes"
SCP="scp -i $DEPLOY_KEY -P $DEPLOY_PORT -o BatchMode=yes"
# .user.ini is a dotfile (not matched by *.php) so it is listed explicitly.
$SCP server/php/*.php server/php/.user.ini "$DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH/"
# Static assets (dashboard logo watermark, etc.)
$SSH "$DEPLOY_USER@$DEPLOY_HOST" "mkdir -p $DEPLOY_PATH/assets"
$SCP server/php/assets/* "$DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH/assets/"
# Retire the old public folder-scan page so index.php becomes the directory index;
# chown only where we have root (DEPLOY_CHOWN is empty on shared hosting).
CHOWN_CMD=true
[ -n "${DEPLOY_CHOWN:-}" ] && CHOWN_CMD="chown -R $DEPLOY_CHOWN $DEPLOY_PATH"
$SSH "$DEPLOY_USER@$DEPLOY_HOST" "rm -f $DEPLOY_PATH/index.html; $CHOWN_CMD"

echo ""
echo "==================================================="
echo "  Deployed Teamwork Show  v$VERSION  ($DATE)"
echo "  App     -> installed on the connected device"
echo "  Server  -> $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH"
echo "==================================================="
